name: deep_front
filters:
  - name: Deep2019Filter
    parameters:
      - name: Enable
        value: 1
      - name: Debug contour
        value: 1
      - name: bat
        value: 0
      - name: wolf
        value: 0
      - name: vetalas
        value: 0
      - name: draugr
        value: 0
      - name: jiangshi
        value: 1
      - name: answag
        value: 0
      - name: vampire
        value: 0
