name: simple_test
filters:
  - name: ContrastAndBrightnessFilter
    parameters:
      - name: enable
        value: 0
      - name: Contrast
        value: 0.000000
      - name: Brightness
        value: 0.000000
  - name: SubtractAllPlanesFilter
    parameters:
      - name: enable
        value: 1
      - name: Plane 1
        value: 4
      - name: Plane 2
        value: 0
      - name: Plane 3
        value: 0
      - name: Invert plane 1
        value: 0
      - name: Invert plane 2
        value: 0
      - name: Invert plane 3
        value: 0
      - name: Weight plane 1
        value: 1.000000
      - name: Weight plane 2
        value: 1.000000
      - name: Weight plane 3
        value: 1.000000
  - name: ThresholdFilter
    parameters:
      - name: Enable
        value: 0
      - name: Threshold type
        value: 1
      - name: Maximum value
        value: 50
  - name: IntervalThresholdFilter
    parameters:
      - name: Enable
        value: 1
      - name: Threshold type_
        value: 1
      - name: Minimum value 1
        value: 50
      - name: Minimum value 2
        value: 55
  - name: SubtractAllPlanesFilter
    parameters:
      - name: enable
        value: 1
      - name: Plane 1
        value: 7
      - name: Plane 2
        value: 0
      - name: Plane 3
        value: 0
      - name: Invert plane 1
        value: 0
      - name: Invert plane 2
        value: 0
      - name: Invert plane 3
        value: 0
      - name: Weight plane 1
        value: 1.000000
      - name: Weight plane 2
        value: 1.000000
      - name: Weight plane 3
        value: 1.000000
  - name: PipeAngleDetector
    parameters:
      - name: Enable
        value: 1
      - name: Debug contour
        value: 1
      - name: Minimum area
        value: 10000.000000
      - name: Minimum pixel
        value: 100.000000