name: simple_jiangshi_backup
filters:
  - name: SubtractAllPlanesFilter
    parameters:
      - name: enable
        value: 1
      - name: Plane 1
        value: 7
      - name: Plane 2
        value: 0
      - name: Plane 3
        value: 0
      - name: Invert plane 1
        value: 0
      - name: Invert plane 2
        value: 0
      - name: Invert plane 3
        value: 0
      - name: Weight plane 1
        value: 1.000000
      - name: Weight plane 2
        value: 1.000000
      - name: Weight plane 3
        value: 1.000000
  - name: ThresholdFilter
    parameters:
      - name: Enable
        value: 1
      - name: Threshold type
        value: 1
      - name: Maximum value
        value: 100
  - name: VampireTorpedoesDetector
    parameters:
      - name: Enable
        value: 1
      - name: Debug contour
        value: 1
      - name: Look for ellipse
        value: 1
      - name: Look_for_Heart
        value: 0
      - name: Minimum area
        value: 5000.000000
      - name: Maximum area
        value: 100000.000000