name: simple_pipe45
filters:
  - name: RotateFilter
    parameters:
      - name: Enable
        value: 0
      - name: Transpose
        value: 0
      - name: Rotation type
        value: 3
  - name: CropFilter
    parameters:
      - name: Enable
        value: 0
      - name: X Offset
        value: 281
      - name: Y Offset
        value: 0
      - name: X Reduction
        value: 245
      - name: Y Reduction
        value: 17
  - name: ContrastAndBrightnessFilter
    parameters:
      - name: Enable
        value: 0
      - name: Contrast
        value: 1.400000
      - name: Brightness
        value: -134.000000
  - name: SubtractAllPlanesFilter
    parameters:
      - name: Enable
        value: 1
      - name: Plane 1
        value: 3
      - name: Plane 2
        value: 3
      - name: Plane 3
        value: 4
      - name: Invert plane 1
        value: 0
      - name: Invert plane 2
        value: 0
      - name: Invert plane 3
        value: 0
      - name: Weight plane 1
        value: 2.000000
      - name: Weight plane 2
        value: 0.000000
      - name: Weight plane 3
        value: 2.000000
  - name: ThresholdFilter
    parameters:
      - name: Enable
        value: 1
      - name: Threshold type
        value: 0
      - name: Maximum value
        value: 50
  - name: ErodeFilter
    parameters:
      - name: Enable
        value: 0
      - name: Square kernel
        value: 1
      - name: Kernel type
        value: 0
      - name: Width
        value: 3
      - name: Height
        value: 1
      - name: Iteration
        value: 2
  - name: BlurFilter
    parameters:
      - name: Enable
        value: 1
      - name: Type
        value: 2
      - name: Kernel size
        value: 21
  - name: ThresholdFilter
    parameters:
      - name: Enable
        value: 1
      - name: Threshold type
        value: 0
      - name: Maximum value
        value: 100
  - name: PipeAngleDetector
    parameters:
      - name: Enable
        value: 1
      - name: Debug contour
        value: 1
      - name: Minimum area
        value: 1000.000000
      - name: Minimum pixel
        value: 100.000000