name: simple_coffin_handle
filters:
  - name: CropFilter
    parameters:
      - name: Enable
        value: 0
      - name: X Offset
        value: 264
      - name: Y Offset
        value: 0
      - name: X Reduction
        value: 251
      - name: Y Reduction
        value: 0
  - name: SubtractAllPlanesFilter
    parameters:
      - name: enable
        value: 1
      - name: Plane 1
        value: 2
      - name: Plane 2
        value: 4
      - name: Plane 3
        value: 0
      - name: Invert plane 1
        value: 0
      - name: Invert plane 2
        value: 0
      - name: Invert plane 3
        value: 0
      - name: Weight plane 1
        value: 1.000000
      - name: Weight plane 2
        value: 1.000000
      - name: Weight plane 3
        value: 1.000000
  - name: ThresholdFilter
    parameters:
      - name: Enable
        value: 1
      - name: Threshold type
        value: 1
      - name: Maximum value
        value: 0
  - name: DilateFilter
    parameters:
      - name: Enable
        value: 0
      - name: Square kernel
        value: 1
      - name: Kernel type
        value: 0
      - name: Width
        value: 1
      - name: Height
        value: 1
      - name: Iteration
        value: 1
  - name: BlurFilter
    parameters:
      - name: Enable
        value: 1
      - name: Type
        value: 3
      - name: Kernel size
        value: 8
  - name: VampireBodyDetector
    parameters:
      - name: Enable
        value: 1
      - name: Debug contour
        value: 1
      - name: Look for rectangle
        value: 0
      - name: Minimum area
        value: 5000.000000
      - name: Maximum area
        value: 15000.000000