name: simple_buoy_green
filters:
  - name: Rotate
    parameters:
      - name: enable
        value: 0
      - name: transpose
        value: 0
      - name: Rotation_type
        value: 3
  - name: ContrastBrightness
    parameters:
      - name: enable
        value: 1
      - name: Contrast
        value: 5.000000
      - name: Brightness
        value: -60.000000
  - name: SubtractAllPlanes
    parameters:
      - name: enable
        value: 1
      - name: Plane_1
        value: 2
      - name: Plane_2
        value: 3
      - name: Plane_3
        value: 4
      - name: Invert_plane_1
        value: 0
      - name: Invert_plane_2
        value: 0
      - name: Invert_plane_3
        value: 0
      - name: Weight_Plane_1
        value: 1.100000
      - name: Weight_Plane_2
        value: 1.200000
      - name: Weight_Plane_3
        value: 1.000000
  - name: Equalize
    parameters:
      - name: enable
        value: 0
  - name: Blurr
    parameters:
      - name: Enable
        value: 1
      - name: Type
        value: 2
      - name: Kernel_size
        value: 3
  - name: StatsThreshold
    parameters:
      - name: Enable
        value: 0
      - name: Min_thresh
        value: 0
      - name: Mean_multiplier
        value: 1.000000
      - name: Standard_deviation_multiplier
        value: 1.000000
  - name: Threshold
    parameters:
      - name: Enable
        value: 1
      - name: Threshold_type
        value: 0
      - name: Max_value
        value: 26
  - name: Morphology
    parameters:
      - name: Enable
        value: 1
      - name: Morphology_type
        value: 3
      - name: Kernel_type
        value: 0
      - name: Iteration
        value: 2
      - name: Kernel_size
        value: 3
  - name: Erode
    parameters:
      - name: Enable
        value: 1
      - name: Square_kernel
        value: 1
      - name: Kernel_type
        value: 0
      - name: Width
        value: 1
      - name: Height
        value: 1
      - name: Iteration
        value: 1
  - name: Dilate
    parameters:
      - name: Enable
        value: 1
      - name: Square_kernel
        value: 1
      - name: Kernel_type
        value: 0
      - name: Width
        value: 1
      - name: Height
        value: 1
      - name: Iteration
        value: 1
  - name: ObjectFinder
    parameters:
      - name: Enable
        value: 1
      - name: Debug_contour
        value: 1
      - name: Use_convex_hull
        value: 1
      - name: Offset Y for fence
        value: 0
      - name: Offset Y for fence fraction
        value: 0.300000
      - name: 0. Check max y
        value: 1
      - name: 0. Maximum y coordinate
        value: 200.000000
      - name: "1. Min_area : red"
        value: 50.000000
      - name: "2. disable_ratio_check : blue"
        value: 1
      - name: 2. Ratio_target
        value: 1.000000
      - name: 2. Diff_from_ratio_target
        value: 0.300000
      - name: "3. Min_percent_filled : yellow"
        value: 40.000000
      - name: "4.1 Look_for_Rectangle : green"
        value: 0
      - name: "4.2 disable_angle_check : green"
        value: 1
      - name: 4.2 angle_target
        value: 0.000000
      - name: 4.2 Diff_from_angle_target
        value: 30.000000
      - name: 5. Eliminate_same_x
        value: 1
      - name: 5. Min_x_difference
        value: 50.000000
      - name: Vote_most_centered
        value: 0
      - name: Vote_most_upright
        value: 0
      - name: Vote_less_diff_from_target_ratio
        value: 1
      - name: Vote_length
        value: 0
      - name: Vote_higher
        value: 1
      - name: Vote most horizontal
        value: 0
      - name: ID
        value: buoy
      - name: spec1
        value: red
      - name: spec2
        value: blue
      - name: Contour_retreval
        value: 0